const MESSAGE = {
	CREATE_ROOM: 'CREATE_ROOM',
	JOIN_ROOM: 'JOIN_ROOM',
	LEAVE_ROOM: 'LEAVE_ROOM',
	USER_LEFT: 'USER_LEFT',
	START_GAME: 'START_GAME',
	SUBMIT_STROKE: 'SUBMIT_STROKE',
	NEW_TURN: 'NEW_TURN',
	SUBMIT_VOTE: 'SUBMIT_VOTE',
	VOTE_RESULT: 'VOTE_RESULT',
	NEXT_ROUND: 'NEXT_ROUND',
	RETURN_TO_SETUP: 'RETURN_TO_SETUP',
	ADD_CUSTOM_TOPIC: 'ADD_CUSTOM_TOPIC',
	REMOVE_CUSTOM_TOPIC: 'REMOVE_CUSTOM_TOPIC',
	TOGGLE_CUSTOM_TOPICS: 'TOGGLE_CUSTOM_TOPICS',
};

export default MESSAGE;
