const MESSAGE = {
	CREATE_ROOM: 'CREATE_ROOM',
	JOIN_ROOM: 'JOIN_ROOM',
	LEAVE_ROOM: 'LEAVE_ROOM',
	USER_LEFT: 'USER_LEFT',
	START_GAME: 'START_GAME',
	SUBMIT_STROKE: 'SUBMIT_STROKE',
	NEW_TURN: 'NEW_TURN',
	SUBMIT_VOTE: 'SUBMIT_VOTE',
	VOTE_RESULT: 'VOTE_RESULT',
	NEXT_ROUND: 'NEXT_ROUND',
	RETURN_TO_SETUP: 'RETURN_TO_SETUP',
	ADD_CUSTOM_TOPIC: 'ADD_CUSTOM_TOPIC',
	REMOVE_CUSTOM_TOPIC: 'REMOVE_CUSTOM_TOPIC',
	TOGGLE_CUSTOM_TOPICS: 'TOGGLE_CUSTOM_TOPICS',
	SET_GAME_MODE: 'SET_GAME_MODE',
	TURN_TIMER_UPDATE: 'TURN_TIMER_UPDATE',
	LOBBY_COUNTDOWN_UPDATE: 'LOBBY_COUNTDOWN_UPDATE',
	LOBBY_EMOTE: 'LOBBY_EMOTE',
	LOBBY_ACTIVITY: 'LOBBY_ACTIVITY',
} as const;

export type MessageName = (typeof MESSAGE)[keyof typeof MESSAGE];

export default MESSAGE;
